spring.application.name=ICT_Project2_KimSatGat
server.port=8082

spring.datasource.url=jdbc:oracle:thin:@satgatbase_high?TNS_ADMIN=wallet/Wallet_SATGATBASE
spring.datasource.username=admin
spring.datasource.password=Tjfltjsdn910
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

logging.level.org.mybatis=DEBUG

mybatis.mapper-locations=Mapper/*.xml
mybatis.type-aliases-package=org.seongsu.satgatproject
mybatis.configuration.map-underscore-to-camel-case=true

#### jsp 
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp